/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\projects\\橘子互联\\前端技术规范\\前端代码规范文档\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-d36023dc",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d36023dc").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-4489ed13",
    path: "/decorete.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4489ed13").then(next)
    },
  },
  {
    name: "v-f903d1ae",
    path: "/problem.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f903d1ae").then(next)
    },
  },
  {
    name: "v-681033d4",
    path: "/decorete/01-aaa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-681033d4").then(next)
    },
  },
  {
    name: "v-7b2f0f69",
    path: "/extends.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b2f0f69").then(next)
    },
  },
  {
    name: "v-1dfe086e",
    path: "/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1dfe086e").then(next)
    },
  },
  {
    name: "v-1f92a569",
    path: "/structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f92a569").then(next)
    },
  },
  {
    name: "v-75efed49",
    path: "/subject.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75efed49").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]