// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CalStickyLayout: typeof import('./src/components/Bases/CalStickyLayout/index.vue')['default']
    ColorFulPickr: typeof import('./src/components/Bases/ColorFulPickr/index.vue')['default']
    ColorPickr: typeof import('./src/components/Bases/ColorPickr/index.vue')['default']
    ModalTemplate: typeof import('./src/components/Bases/ModalTemplate/index.vue')['default']
    NestedSortTable: typeof import('./src/components/Bases/NestedSortTable/index.vue')['default']
    QrCode: typeof import('./src/components/Bases/QrCode/index.vue')['default']
    TinymceEditor: typeof import('./src/components/Bases/TinymceEditor/index.vue')['default']
    ConsolePayment: typeof import('./src/components/Business/ConsolePayment/index.vue')['default']
    CalImage: typeof import('./src/components/CustomAntds/CalImage/index.vue')['default']
    CalTabPane: typeof import('./src/components/CustomAntds/CalTabPane/index.vue')['default']
    CalTabs: typeof import('./src/components/CustomAntds/CalTabs/index.vue')['default']
    ColorPickr__elPicker: typeof import('./src/components/Bases/ColorPickr/color-pickr(@simonwep)/color-pickr__el-picker.vue')['default']
    ColorPickr__simonwepPickr: typeof import('./src/components/Bases/ColorPickr/color-pickr(@simonwep)/color-pickr__simonwep-pickr.vue')['default']
  }
}

export { }
