/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "F:\\projects\\橘子互联\\前端技术规范\\前端代码规范文档\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "F:\\projects\\橘子互联\\前端技术规范\\前端代码规范文档\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "F:\\projects\\橘子互联\\前端技术规范\\前端代码规范文档\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2
]