/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "橘子互联前端代码规范文档",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "shortcut icon",
        "type": "image/x-icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Front-End Coding Guidelines",
        "heroImage": "/hero.png",
        "tagline": null,
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "HTML 规范",
            "details": "基于凹凸实验室官方文档，并结合团队日常业务需求以及团队在日常开发过程中总结提炼出的经验而约定。"
          },
          {
            "title": "CSS 规范",
            "details": "统一团队 CSS 代码书写和 SASS 预编译语言的语法风格，并从业务层面统一规范常用模块的引用。"
          },
          {
            "title": "JavaScript 规范",
            "details": "统一团队的 JS 语法风格和书写习惯，减少程序出错的概率，其中也包含了 ES6 的语法规范和最佳实践。"
          },
          {
            "title": "TypeScript 规范",
            "details": "统一团队的 TS 类型的定义，第三方库的使用，请求与响应参数的约定。"
          },
          {
            "title": "知识扩展",
            "details": "用于新同事如何快速切入项目，项目开发技术的学习路线。"
          },
          {
            "title": "常见问题",
            "details": "总结日常开发出现的疑难杂症，避免二次踩坑。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-d36023dc",
      "path": "/"
    },
    {
      "title": "装修页面/组件",
      "frontmatter": {
        "sidebar": "auto",
        "title": "装修页面/组件"
      },
      "regularPath": "/decorete.html",
      "relativePath": "decorete.md",
      "key": "v-4489ed13",
      "path": "/decorete.html",
      "headers": [
        {
          "level": 2,
          "title": "开发说明",
          "slug": "开发说明"
        },
        {
          "level": 3,
          "title": "项目结构",
          "slug": "项目结构"
        },
        {
          "level": 3,
          "title": "基本 component 视图描述",
          "slug": "基本-component-视图描述"
        },
        {
          "level": 2,
          "title": "页面创建",
          "slug": "页面创建"
        },
        {
          "level": 3,
          "title": "配置流程与规范",
          "slug": "配置流程与规范"
        },
        {
          "level": 3,
          "title": "新组件开发流程 and 创建页面流程",
          "slug": "新组件开发流程-and-创建页面流程"
        },
        {
          "level": 2,
          "title": "操作区",
          "slug": "操作区"
        },
        {
          "level": 3,
          "title": "引入option配置",
          "slug": "引入option配置"
        },
        {
          "level": 3,
          "title": "开发以及组件的使用",
          "slug": "开发以及组件的使用"
        },
        {
          "level": 3,
          "title": "目前已有组件",
          "slug": "目前已有组件"
        },
        {
          "level": 3,
          "title": "组件定义规范",
          "slug": "组件定义规范"
        },
        {
          "level": 2,
          "title": "视图区",
          "slug": "视图区"
        },
        {
          "level": 3,
          "title": "钩子使用(引入)",
          "slug": "钩子使用-引入"
        },
        {
          "level": 3,
          "title": "钩子使用(模板)",
          "slug": "钩子使用-模板"
        },
        {
          "level": 3,
          "title": "view-image组件",
          "slug": "view-image组件"
        },
        {
          "level": 3,
          "title": "view-image图片和图标显示问题",
          "slug": "view-image图片和图标显示问题"
        },
        {
          "level": 3,
          "title": "兼容写法",
          "slug": "兼容写法"
        },
        {
          "level": 3,
          "title": "样式兼容",
          "slug": "样式兼容"
        },
        {
          "level": 3,
          "title": "C端页面创建",
          "slug": "c端页面创建"
        },
        {
          "level": 2,
          "title": "其他问题",
          "slug": "其他问题"
        },
        {
          "level": 3,
          "title": "修改旧组件兼容问题",
          "slug": "修改旧组件兼容问题"
        }
      ]
    },
    {
      "title": "常见问题",
      "frontmatter": {},
      "regularPath": "/problem.html",
      "relativePath": "problem.md",
      "key": "v-f903d1ae",
      "path": "/problem.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/decorete/01-aaa.html",
      "relativePath": "decorete/01-aaa.md",
      "key": "v-681033d4",
      "path": "/decorete/01-aaa.html"
    },
    {
      "title": "知识扩展",
      "frontmatter": {
        "sidebar": "auto",
        "title": "知识扩展"
      },
      "regularPath": "/extends.html",
      "relativePath": "extends.md",
      "key": "v-7b2f0f69",
      "path": "/extends.html",
      "headers": [
        {
          "level": 2,
          "title": "基本",
          "slug": "基本"
        },
        {
          "level": 2,
          "title": "开发框架",
          "slug": "开发框架"
        },
        {
          "level": 3,
          "title": "Vue 技术栈",
          "slug": "vue-技术栈"
        },
        {
          "level": 3,
          "title": "服务端渲染",
          "slug": "服务端渲染"
        },
        {
          "level": 3,
          "title": "多端开发",
          "slug": "多端开发"
        },
        {
          "level": 2,
          "title": "UI组件库",
          "slug": "ui组件库"
        },
        {
          "level": 2,
          "title": "开发工具",
          "slug": "开发工具"
        },
        {
          "level": 2,
          "title": "时间处理",
          "slug": "时间处理"
        },
        {
          "level": 2,
          "title": "移动端调试",
          "slug": "移动端调试"
        },
        {
          "level": 2,
          "title": "数据可视化",
          "slug": "数据可视化"
        },
        {
          "level": 2,
          "title": "独立UI组件",
          "slug": "独立ui组件"
        }
      ]
    },
    {
      "title": "橘子互联前端代码规范文档(v0.8)",
      "frontmatter": {
        "sidebar": "auto",
        "title": "橘子互联前端代码规范文档(v0.8)"
      },
      "regularPath": "/guide.html",
      "relativePath": "guide.md",
      "key": "v-1dfe086e",
      "path": "/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "CSS/SCSS 规范",
          "slug": "css-scss-规范"
        },
        {
          "level": 3,
          "title": "Class命名",
          "slug": "class命名"
        },
        {
          "level": 3,
          "title": "全局样式（主体色）",
          "slug": "全局样式-主体色"
        },
        {
          "level": 3,
          "title": "避免事项",
          "slug": "避免事项"
        },
        {
          "level": 3,
          "title": "CSS 属性书写顺序",
          "slug": "css-属性书写顺序"
        },
        {
          "level": 2,
          "title": "JavaScript 规范",
          "slug": "javascript-规范"
        },
        {
          "level": 3,
          "title": "变量/函数命名",
          "slug": "变量-函数命名"
        },
        {
          "level": 3,
          "title": "变量引用",
          "slug": "变量引用"
        },
        {
          "level": 3,
          "title": "模块化开发",
          "slug": "模块化开发"
        },
        {
          "level": 3,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 3,
          "title": "if ... else",
          "slug": "if-else"
        },
        {
          "level": 2,
          "title": "TypeScript 规范",
          "slug": "typescript-规范"
        },
        {
          "level": 3,
          "title": "类型定义",
          "slug": "类型定义"
        },
        {
          "level": 3,
          "title": "第三方库",
          "slug": "第三方库"
        },
        {
          "level": 3,
          "title": "全局类型",
          "slug": "全局类型"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "响应参数",
          "slug": "响应参数"
        }
      ]
    },
    {
      "title": "基本环境搭建",
      "frontmatter": {},
      "regularPath": "/structure.html",
      "relativePath": "structure.md",
      "key": "v-1f92a569",
      "path": "/structure.html",
      "headers": [
        {
          "level": 2,
          "title": "基本环境搭建",
          "slug": "基本环境搭建"
        },
        {
          "level": 2,
          "title": "项目构建说明",
          "slug": "项目构建说明"
        },
        {
          "level": 2,
          "title": "当前机器Git密匙配置",
          "slug": "当前机器git密匙配置"
        },
        {
          "level": 2,
          "title": "当前项目路径",
          "slug": "当前项目路径"
        },
        {
          "level": 2,
          "title": "项目模板说明",
          "slug": "项目模板说明"
        },
        {
          "level": 3,
          "title": "uni-app 项目模板使用说明",
          "slug": "uni-app-项目模板使用说明"
        },
        {
          "level": 3,
          "title": "web-vue@3 项目模板使用说明",
          "slug": "web-vue-3-项目模板使用说明"
        },
        {
          "level": 3,
          "title": "多端开发框架Vue3兼容对比表",
          "slug": "多端开发框架vue3兼容对比表"
        },
        {
          "level": 3,
          "title": "其他模板拷贝指令",
          "slug": "其他模板拷贝指令"
        }
      ]
    },
    {
      "title": "1rem、1em、1vh、1px各自代表的含义？",
      "frontmatter": {},
      "regularPath": "/subject.html",
      "relativePath": "subject.md",
      "key": "v-75efed49",
      "path": "/subject.html",
      "headers": [
        {
          "level": 3,
          "title": "1rem、1em、1vh、1px各自代表的含义？",
          "slug": "_1rem、1em、1vh、1px各自代表的含义"
        },
        {
          "level": 3,
          "title": "css水平、垂直居中的写法，请至少说出3~4种？",
          "slug": "css水平、垂直居中的写法-请至少说出3-4种"
        },
        {
          "level": 3,
          "title": "说一下闭包？",
          "slug": "说一下闭包"
        },
        {
          "level": 3,
          "title": "说一下自己常用的es6~es11的功能？",
          "slug": "说一下自己常用的es6-es11的功能"
        },
        {
          "level": 3,
          "title": "说说你经常用的小程序/Uniapp的生命周期函数",
          "slug": "说说你经常用的小程序-uniapp的生命周期函数"
        },
        {
          "level": 3,
          "title": "关于箭头函数，下面说法错误的有哪些？",
          "slug": "关于箭头函数-下面说法错误的有哪些"
        },
        {
          "level": 3,
          "title": "请说明以下代码的执行结果以及this的指向",
          "slug": "请说明以下代码的执行结果以及this的指向"
        },
        {
          "level": 3,
          "title": "假设以下两个异步请求接口 cgia、cgib 返回结果均为整数，请编写代码输出 result.data.a 和 result.data.b 相加的值",
          "slug": "假设以下两个异步请求接口-cgi-a、cgi-b-返回结果均为整数-请编写代码输出-result-data-a-和-result-data-b-相加的值"
        },
        {
          "level": 3,
          "title": "Vue3.0 里为什么要用 Proxy API 替代 defineProperty API？",
          "slug": "vue3-0-里为什么要用-proxy-api-替代-defineproperty-api"
        },
        {
          "level": 3,
          "title": "Vue Composition API 的基本使用",
          "slug": "vue-composition-api-的基本使用"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/hero.png",
    "nav": [
      {
        "text": "规范文档",
        "link": "/guide"
      },
      {
        "text": "项目文档",
        "items": [
          {
            "text": "环境配置/项目构建",
            "link": "/structure"
          },
          {
            "text": "装修规范/装修组件",
            "link": "/decorete/"
          }
        ]
      },
      {
        "text": "知识扩展",
        "link": "/extends"
      },
      {
        "text": "站外链接",
        "items": [
          {
            "text": "Gitee",
            "link": "https://gitee.com/juzihulian_1/front_end_docs"
          },
          {
            "text": "TypeScript",
            "link": "https://www.tslang.cn/"
          },
          {
            "text": "UniApp",
            "link": "https://uniapp.dcloud.io/"
          },
          {
            "text": "Vue2.0",
            "link": "https://cn.vuejs.org/"
          },
          {
            "text": "Vue3.0",
            "link": "https://v3.cn.vuejs.org/"
          },
          {
            "text": "Mr.Mao's blog",
            "link": "https://tuimao233.gitee.io/mao-blog/"
          }
        ]
      },
      {
        "text": "常见问题",
        "link": "/problem"
      }
    ],
    "sidebar": {
      "/decorete/": [
        {
          "title": "啊啊",
          "path": "01-aaa"
        }
      ]
    }
  }
}